ci:
  autofix_prs: true
  autoupdate_schedule: monthly
  # These hooks require a Rust toolchain and are handled in GHA CI.
  skip: [cargo-fmt, cargo-clippy]

repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.45.1
    hooks:
      - id: typos

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [--strict, -c, .yamllint.yaml]
        files: (.github/|.codecov.yaml|.pre-commit-config.yaml|.yamllint.yaml)

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: cargo fmt --
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        language: system
        entry: cargo clippy --all-targets -- -D warnings
        types: [rust]
        pass_filenames: false
